package com.example.veterinaryclinicsuperpets.entity.enums;

public enum UserType {
  // NEED THIS FOR REGISTRATION
  // WHEN SOMEONE IS REGISTERING FROM THE WEB PAGE WILL AUTOMATICALLY SET USER TYPE TO CLIENT
  // ADMIN CAN REGISTER OTHER ADMIN OR VET
  // THIS IS IMPORTANT ABOUT THE RIGHTS OF THE USER IN THE PLATFORM
  CLIENT,
  VET,
  ADMIN
}
